macos fix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -103,18 +103,6 @@ runs:
         echo "----------------------------------------------------"
       shell: bash
       if: ${{ env.FILE_DIFF == '' && inputs.files == '' }}
-    
-
-
-    - name: Configure fail fast
-      run: |
-        fail_fast="|| true"
-        if [[ "${{ inputs.fail-fast }}" == 'y' || "${{ inputs.fail-fast }}" == 'Y' ]]; then
-          fail_fast=""
-        fi
-        echo "FAIL_FAST=$fail_fast" >> "$GITHUB_ENV"
-      shell: bash
-      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
 
 
 
@@ -198,7 +186,11 @@ runs:
         do
           echo "----------------------------------------------------"
           echo "Running ESBMC on $path"
-          $time $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} "$path" $FAIL_FAST
+          if [[ "${{ inputs.fail-fast }}" == 'y' || "${{ inputs.fail-fast }}" == 'Y' ]]; then
+            $time $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} "$path" $FAIL_FAST
+          else
+            $time $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} "$path" $FAIL_FAST || true
+          fi
 
           if [[ -f "$GOTO_FILENAME" ]]; then
             mv "$GOTO_FILENAME" "$path""__""$NOSPACE_GOTO_FILENAME"
@@ -348,7 +340,11 @@ runs:
         do
           echo "----------------------------------------------------"
           echo "Running ESBMC on $path"
-          $timer $GITHUB_WORKSPACE/bin/esbmc --smtlib --smt-formula-only ${{ inputs.esbmc-options }} "$path" $FAIL_FAST
+          if [[ "${{ inputs.fail-fast }}" == 'y' || "${{ inputs.fail-fast }}" == 'Y' ]]; then
+            $timer $GITHUB_WORKSPACE/bin/esbmc --smtlib --smt-formula-only ${{ inputs.esbmc-options }} "$path"
+          else
+            $timer $GITHUB_WORKSPACE/bin/esbmc --smtlib --smt-formula-only ${{ inputs.esbmc-options }} "$path" || true
+          fi
 
           if [[ -f "$GOTO_FILENAME" ]]; then
             mv "$GOTO_FILENAME" "$path""__""$NOSPACE_GOTO_FILENAME"
